version: "3.8"

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.12-bookworm
    volumes:
      - ..:/workspaces/hi5304-notebooks:cached
    working_dir: /workspaces/hi5304-notebooks
    command: sleep infinity
    depends_on:
      - db

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: hi5304
      POSTGRES_USER: hi5304_user
      POSTGRES_PASSWORD: hi5304_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
